//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyInfoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class IP_Info
    {
        public decimal SerialNo { get; set; }
        public string IPv4 { get; set; }
        public string Proxy { get; set; }
        public string Proxy_Port { get; set; }
        public string IPv4_Address { get; set; }
        public string IPv4_City { get; set; }
        public string IPv4_State { get; set; }
        public string IPv4_Country { get; set; }
        public string IPv4_Category { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string InsertedBy { get; set; }
        public string IPv4_Speed { get; set; }
        public string ASNUM { get; set; }
        public string ORG_NAME { get; set; }
        public string POSTAL_CODE { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string TZ { get; set; }
    }
}
